name: auto-pull-vps
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pull-newest-commit:
    if: github.actor != 'petaxa-vps'
    runs-on: ubuntu-22.04

    steps:
      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Pull newest commit on VPS
        run: |
          ssh -p ${{ secrets.VPS_PORT }} \
              -o StrictHostKeyChecking=no \
              tempest@${{ secrets.VPS_IP }} \
              'cd ~/Documents/expo-2025-waiting-time-json && git pull'
